node ('master') {
 	set M2_HOME='C:\Users\subodh\Programs\apache-maven-3.6.0-bin\apache-maven-3.6.0'
	set path='C:\Users\subodh\Programs\apache-maven-3.6.0-bin\apache-maven-3.6.0\bin:%path%;'
	
	    timeout(1) {
     
    		dir('project-manager-app/project-manager-app') {
	    
		        stage('Checkout') {
		           echo 'Checkout'
		           git branch: 'master', url: 'https://github.com/subodhsubhedar/project-manager-app.git'
		        }
		    
		        stage('Build') 
		         	maven : 'Maven'	 
		            echo 'Build'
		            bat 'mvn clean compile'
		        }
		        
		        stage('Test') {
		            echo 'Test'
		            bat 'mvn test'
		        }
		     
		        stage('Package') {
		            echo 'Package'
		            bat 'mvn package'
		        }
		     
		        stage('Deploy') {
		    
		            echo 'Deploy'
		        }
		    
		        stage('Archive') {
		                echo 'Archive'
		            archiveArtifacts '/target/*.jar'
		        }
	    	}
}   
